name: THÊM UPLOAD KERNEL TELEGRAM

on:
  workflow_dispatch:

jobs:
  patch-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Destination Repo
        uses: actions/checkout@v4
        with:
          repository: BEACHEADVN/GKI_KernelSU_SUSFS
          token: ${{ secrets.GH_PAT }}
          path: remote-repo

      - name: THÊM UPLOAD KERNEL TELEGRAM
        run: |
         cd remote-repo/.github/workflows/

         echo "--- Kiểm tra đã chèn chưa ---"
         if grep -q "CHUẨN BỊ AnyKernel3 zip CHO TELEGRAM" build.yml; then
         echo "Đã tồn tại, bỏ qua."
         else
         echo "Tải file từ My-Assets..."
         curl -L -o add_upload_telegram.txt \
          https://raw.githubusercontent.com/BEACHEADVN/My-Assets/main/Wild_KSU/ADD_UPLOAD_TELEGRAM.txt
          echo "--- Nội dung file ---"
          cat add_upload_telegram.txt
          echo "Chèn vào build.yml..."
          awk '/^[[:space:]]*# End of workflow/{system("cat add_upload_telegram.txt")}1' build.yml > tmp && mv tmp build.yml
          echo "Chèn thành công."
          fi
      - name: Push Changes
        run: |
          cd remote-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet; then
            echo "Không có thay đổi nào để push."
          else
            git add .github/workflows/build.yml
            git commit -m "THÊM UPLOAD KERNEL TELEGRAM"
            git push origin HEAD:main
          fi

      - name: KIỂM TRA
        run: |
          cd remote-repo/.github/workflows/
          cat build.yml
