name: LỌC CÁC PHIÊN BẢN KERNEL 5.15 ANDROID 13
on:
  workflow_dispatch:

jobs:
  patch-file-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Destination Repo
        uses: actions/checkout@v4
        with:
          repository: BEACHEADVN/GKI_KernelSU_SUSFS
          token: ${{ secrets.GH_PAT }}
          path: remote-repo

      - name: LỌC
        run: |
          cd remote-repo/
          FILE_PATH=".github/kernel-config/a13-5.15.json"
          
          echo "--- Nội dung gốc (3 dòng đầu) ---"
          head -n 5 $FILE_PATH
          
          # Dùng jq để lọc chỉ giữ lại 5.15.170 và 5.15.189
          # Lệnh này ghi đè trực tiếp vào file tạm rồi chuyển ngược lại file gốc
          jq '.include |= map(select(.kernel_version | contains("5.15.170") or contains("5.15.189")))' $FILE_PATH > temp.json && mv temp.json $FILE_PATH
          
          echo "--- Nội dung sau khi lọc ---"
          cat $FILE_PATH
          
      - name: Push Changes
        run: |
          cd remote-repo/.github/workflows/
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Kiểm tra xem có sự thay đổi nào để commit không
          if git diff --exit-code build.yml > /dev/null; then
            echo "Không có thay đổi nào để push."
          else
            git add build.yml
            git commit -m "Rename FILE_NAME prefix to Ayaka"
            git push origin main
          fi
          
      - name: KIỂM TRA
        run: |
          cd remote-repo/.github/kernel-config
          echo "NỘI DUNG FILE a13-5.15.json"
          cat a13-5.15.json
