name: MOD REPO AYAKA

on:
  workflow_dispatch:

jobs:
  step1:
    uses: BEACHEADVN/My-Assets/.github/workflows/THAY_DOI_ICON_VA_KEY_MANAGER.yml@main

  step2:
    needs: step1
    uses: BEACHEADVN/My-Assets/.github/workflows/LOC_BUILD_LKM_CHO_ANDROID_13 5.15.yml@main

  step3:
    needs: step2
    uses: BEACHEADVN/My-Assets/.github/workflows/LOAI_BO_UPLOAD_MANAGER_LEN_TELEGRAM@main

  step4:
    needs: step3
    uses: BEACHEADVN/My-Assets/.github/workflows/LOAI_BO_DU_THUA_BUILD_MANAGER@main

  step5:
    needs: step4
    uses: BEACHEADVN/My-Assets/.github/workflows/THEM_UPLOAD_MANAGER_TELEGRAM.yml@main
